/// <reference types="vite/client" />
import { DefaultCatchBoundary } from "@/components/DefaultCatchBoundary";
import { NavigationProgress } from "@/components/navigation-progress";
import { NotFound } from "@/components/NotFound";
import { Toaster } from "@/components/ui/sonner";
import { LanguageProvider } from "@/providers";
import appCss from "@/styles/app.css?url";
import { seo } from "@/utils/seo";
import { HeadContent, Scripts, createRootRoute } from "@tanstack/react-router";
import * as React from "react";
import { CookiesProvider } from "react-cookie";

export const Route = createRootRoute({
  head: () => ({
    meta: [
      {
        charSet: "utf-8",
      },
      {
        name: "viewport",
        content: "width=device-width, initial-scale=1",
      },
      ...seo({
        title: "Sasto Sulav Express",
        description: "Generated by create next app",
      }),
    ],
    links: [
      { rel: "stylesheet", href: appCss },
      {
        rel: "apple-touch-icon",
        sizes: "180x180",
        href: "/apple-touch-icon.png",
      },
      {
        rel: "icon",
        type: "image/png",
        sizes: "32x32",
        href: "/favicon-32x32.png",
      },
      {
        rel: "icon",
        type: "image/png",
        sizes: "16x16",
        href: "/favicon-16x16.png",
      },
      { rel: "manifest", href: "/site.webmanifest", color: "#fffff" },
      { rel: "icon", href: "/favicon.ico" },
    ],
    scripts: [
      {
        src: "/customScript.js",
        type: "text/javascript",
      },
    ],
  }),
  errorComponent: DefaultCatchBoundary,
  notFoundComponent: () => <NotFound />,
  shellComponent: RootDocument,
});

function RootDocument({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <head>
        <HeadContent />
      </head>
      <body>
        <CookiesProvider
          defaultSetOptions={{
            path: "/",
          }}
        >
          <LanguageProvider>
            <NavigationProgress />
            {children}
          </LanguageProvider>
        </CookiesProvider>
        <Toaster position="top-center" />
        {/* {process.env.NODE_ENV === "development" && (
          <TanStackRouterDevtools position="bottom-right" />
        )} */}
        <Scripts />
      </body>
    </html>
  );
}
